# The name of our workflow
name: On PRs

on:
  # Trigger on every pull request and on push
  # to the `master` branch.
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Build the app
        run: ./gradlew build
